version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
    groups:
      backend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
    groups:
      frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - '*'
